/** @format */

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import SidebarLayout from './SidebarLayout/SidebarLayout';
import Breadcrumb from '@/components/BreadcrumbBar/breadcrumbBar';
import '@vidstack/react/player/styles/base.css';
import '@vidstack/react/player/styles/plyr/theme.css';
import { ClerkProvider } from '@clerk/nextjs';
const inter = Inter({ subsets: ['latin'] });
import BookLayout from '@/components/BookLayout';

// Define the metadata for the site
export const metadata: Metadata = {
  title: 'iConcepts in Orthodontics',
  description: 'Generated by Next.js',
};

// Define the root layout for the site
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang='en'>
        <body className={inter.className}>
          <div className='px-14 bg-gray-100 w-screen'>
            <Breadcrumb />
          </div>
          <div className='flex w-screen h-screen'>
            <SidebarLayout><BookLayout>{children}</BookLayout></SidebarLayout>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
