# Specify the name of the workflow
name: CI for JavaScript

# Specify events that trigger the workflow
on:
  push:
  pull_request:

# Define the jobs that the workflow will run
jobs:
  # Check whether the version of Node.js is 20.x
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Check the version of Node.js
        run: |
          node -v
          echo "Expected Node.js version: 20.x"
        working-directory: ./frontend

  # Check whether the dependencies are up-to-date
  check-dependencies:
    runs-on: ubuntu-latest
    needs: check-version
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend

  # Build the project
  build:
    runs-on: ubuntu-latest
    needs: check-dependencies
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Build the project
        run: npm run build
        working-directory: ./frontend

  # Lint the code with ESLint
  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Run ESLint
        run: npm run lint
        working-directory: ./frontend

  # Test the code with defined test cases
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Run ESLint
        run: npm run lint
        working-directory: ./frontend

      - name: Run tests
        run: npm run test
        working-directory: ./frontend
